server:
  port: 8881

xxl:
  job:
    admin:
      addresses: http://192.168.200.130:8888/xxl-job-admin
      accessToken: default_token
    executor:
      appname: xxl-job-executor-sample
      port: 9999
