#全局端口定义server:
# 全局字符集设置
spring:
  aop:
    proxy-target-class: true
server:
  tomcat:
    uri-encoding: utf-8
  servlet:
    encoding:
      force: true
      charset: utf-8
      enabled: true

springdoc:
  # 可以用','分割多个需要扫描的包
  packages-to-scan: jmu.lsk.user.controller.v1
  # 可以用','分割多个需要匹配的路径
  # 还可用/hello/**匹配/hello路径及其子路径
  paths-to-match: /api/v1/login/**




